config/routes.rb
Rails.application.routes.draw do

	resources :shipments do
		resources 'skids'
		resources 'forms'
	end
	
root 'shipments#index'

end

app/models/form.rb
class Form < ActiveRecord::Base
	has_many :shipment_forms
	belongs_to :shipment
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
	has_many :skids, dependent: :destroy
	has_many :shipment_forms
	has_many :forms
	accepts_nested_attributes_for :skids, :reject_if => :all_blank, :allow_destroy => true
end

app/models/shipment_form.rb
class ShipmentForm < ActiveRecord::Base
	belongs_to :shipment 
	belongs_to :form
end

app/models/skid.rb
class Skid < ActiveRecord::Base
	belongs_to :shipment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
	def show
		@shipment = Shipment.find_by_id(params[:id])
		@skids = @shipment.skids
		@form = @shipment.form
	end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
	
	def index
		@shipments = Shipment.all
	end

	def show
		@shipment = Shipment.find_by_id(params[:id])
		@skids = @shipment.skids
		@form = Form.find_by_id(params[:idr])
		@total_cases = @skids.sum(:cases)
	end

	def new
		@shipment = Shipment.new
		@shipment.skids.build
		@form = Form.new
	end

	def create
		@shipment = Shipment.new(params[:shipment])
		@form = Form.new(params[:form])

		if @shipment.save
			redirect_to shipment_path(@shipment)
		else
			render :new
		end
	end

	def edit
		@shipment = Shipment.find_by_id(params[:id])
		@skids = @shipment.skids
	end

	def update
		@shipment = Shipment.find_by_id(params[:id])

		if @shipment.update_attributes(shipment_params)
			redirect_to shipment_path(@shipment)
		else
			render :new
		end
	end

	def destroy
		@shipment = Shipment.find_by_id(params[:id])

		if @shipment.destroy
			redirect_to shipments_path
		else
			render :new
		end
		
	end

	def shipment_params
    	params.require(:shipment).permit(:date, :seal, :company, :trucker, :truckernumber, :deliverydate, :day, :truckNumber, skids_attributes: [:id, :shipment_id, :number, :product, :po, :cases, :weight, :breakdown, :_destroy])
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/forms/show.html.erb
<!DOCTYPE html>
<html>
    <head>
        <style type="text/css">
            #header{
                text-align: center;
                font-size: 20px;
            }

            #nyp-address{
                float: left;
            }

            #date{
                float: right;
            }

            #deliver-header{
                clear: both;
                text-align: center;
                font-size: 20px;
            }

            #hubbard-address{
                float: left;
            }

            #date-info{
                float: right;
                font-size: 20px;
            }



            table, th, td{
                border: 1px solid black;
            }

            #shipping-table{
                clear: both;
                width: 100%;

            }

            #pt-one td{
                padding-left: 65px;
                padding-right: 65px;
            }

            #pt-two td{
                padding-left:11px;
                padding-right: 11px
            }

            #star{
                font-size: 8px;
            }

            #comments {
                float: left;
                font-size: 16pt;
            }

            #reciever{
                float: right;
                font-size: 11pt;
            }

            #name-date-time{
                text-align: right;
            }

            #thingy{
                clear: both;
                float:right;
            }

            .fp6px{
                font-size: 6px;
            }

            .fp8px{
                font-size: 8px;
            }

            #fineprint-area{
                clear: both;
            }

            #fineprint-area #caveat{
                width: 50%;
            }

            #fineprint-area #sig-area{
                font-size: 8pt;
            }

            #signature #shipper-sig{
                width: 50%;
            }

            #signature #sig-date{
                margin-right: 70px;
                float:right;
            }

            #signature #ship-sig-fp{
                margin-bottom: 0px;
            }
        </style>
    </head>
    <body>
        <div id = "header">
            <b><u>ORIGINAL BILL OF LADING - NOT NEGOTIABLE</u><b>
        </div>
        <br>
        <div id = "nyp-address">
            <b>NEW YORK PACKAGING</b>
            <br>
            <b>135 FULTON AVENUE</b>
            <br>
            <b>GARDEN CITY PARK, NY 11040</b>
            <br>
            <b>TEL: (516) 746-0600</b>
            <br>
            <b>FAX: (516) 746-0661</b>
        </div>

        <div id = "date">
            <%= @shipment.date %>
        </div>

        <div id = "deliver-header">
            <b><u>DELIVERED</u></b>
        </div>

        <div id = "hubbard-address">
            <b><u>Consignee/Ship to:</u></b>
            <br>
            <b>NEW YORK PACKAGING</b>
            <br>
            <b>REDI BAG USA LLC</b>
            <br>
            <b>734 MYRON STREET</b>
            <br>
            <b>HUBBARD, OH 44425</b>
            <br>
            <b>330-568-4200</b>
        </div>

        <div id = "date-info">
            <b><%= @shipment.day %></b>
            <br>
            <b>TRUCK</b>
            <br>
            <b>NEED POD</b>
        </div>

        <center>
            <div id = "shipping-table">
                <table id="pt-one">
                    <tr>
                        <td>
                            <center>Ship Date</center>
                        </td>
                        <td>
                            <center>Carrier</center>
                        </td>
                        <td>
                            <center>Customer PO No.</center>
                        </td>
                        <td>
                            <center>SO no.</center>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <center><%= @shipment.date %></center>
                        </td>
                        <td>
                            <center>SEAL # <%= @shipment.seal %></center>
                        </td>
                        <td>
                            <center>NYP</center>
                        </td>
                        <td>
                            <center>N/A</center>
                        </td>
                    </tr>
                </table>
                <table id="pt-two">
                    <tr>
                        <td>
                            <center>Item</center>
                        </td>
                        <td>
                            <center>HM*</center>
                        </td>
                        <td>
                            <center>Freight Class</center>
                        </td>
                        <td>
                            <center><u>Description</u></center><br>
                            <center><%= @shipment.trucker %></center><br>
                            <center><%= @shipment.truckernumber %></center><br>
                        </td>
                        <td>
                            <center>Packaging</center>
                        </td>
                        <td>
                            <center>Units</center>
                        </td>
                        <td>
                            <center>Weight</center>
                        </td>
                        <td>
                            Cube
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <center>001</center>
                        </td>
                        <td>
                            <br>
                        </td>
                        <td>
                            <center>156830</center>
                        </td>
                        <td>
                            <center>NYP II LLC</center>
                        </td>
                        <td>
                            <br>
                        </td>
                        <td>
                            <center>XXXXXX</center>
                        </td>
                        <td>
                            <center>XXXXX</center>
                        </td>
                        <td>
                            <br>
                        </td>
                    </tr>
                </table>
            </div>
        </center>

        <div id="star">
            *Items are marked "X" to designate Hazardous Materials as defined in DOT regulations.
        </div>

        <div id="comments">
            <b><u>COMMENTS</u><b>
            <br>
            <br>
            <b>XXXX CASES, XX SKIDS</b>
            <br>
            <b>DELIVERY DATE <%= @shipment.deliverydate %></b>
        </div>

        <div id="reciever">
            <span id="rec-hours">RECEIVING HOURS 8:30AM TO 4:30PM ONLY MON-FRIDAY<span>
            <br>
            <br>
            <div id="name-date-time">
                NAME: ___________________________
                <br>
                <br>
                DATE: ________  TIME: ___________
            </div>
        </div>
        <div id="thingy">
            <div class="header">
            NMFC# 156830, SUB 0 CLASS 55 DENSITY 35LB PCF
            </div>
            <div class="fp6px">
                TO: FREIGHT CARRIERS
                <br>
                BILL OF LADING IS ACCEPTED AS PIECES, NOT PALLETS, WHEN TRANSPOSING BILL OF LADING MUST READ PIECES & NOT PALLETS.
                <br>
                CUSTOMER MUST SIGN FOR # OF PIECES.
                <br>
                FREIGHT CARRIERS MUST SIGN BELOW ACKNOWLEDGING SIGNATURE FOR # OF PIECES.
                <br>
                <br>
            </div>
                FREIGHT CARRIER'S SIGNATURE:_____________________
                <br>
                <br>
                <br>
        </div>
        <div id="fineprint-area">
            <table class="fp8px">
                <tr>
                    <td id="caveat">
                        RECEIVED, subject to the classifications and tariffs in effect on the date of the issue of the Bill of Lading, the property described above, in apparent good order, except as noted (contents and condition of contents of packages unknown), marked, consigned, and destined as indicated below, which said carrier (the word carrier being understood throughout this contract as meaning any person or corporation in possession of the property under the contract) agrees to carry to its usual place of delivery at said destination, if on its route, otherwise to deliver to route to destination, and as to each party at anytime interested in all or any of said of Lading set forth (1) in Uniform Freight Classifications n effect on the date hereof, if this is a rail or rail-water shipment, or (2) the property, that every services to be performed hereunder shall be subject to all the terms and conditions of the Uniform Domestic Straight Bill applicable motor carrier classification or tariff if this is a motor carrier shipment. SHIPPER hereby certifies that he is familiar with all the terms and conditions of the said bill of lading, including those on the back thereof, set forth in the classification or tariff which governs the transportation of this shipment, and the said terms and conditions are hereby agreed to by the shipper and accepted for himself and his ASSIGNS.
                    </td>
                    <td id="sig-area">
                        <center>
                            <b>FREIGHT COLLECT SHIPMENTS.<b>
                            <br>
                            <br>
                            If this shipment is to be delivered to the consignee without recourse
                            <br>
                            on the consignor, the consignor shall sign the following statement:
                            <br>
                            The carrier shall not make delivery of this shipment without payment of freight and all other lawful charges.
                            <br>
                            <br>
                            __________________________________________________
                            <br>
                            (Signature of Cosigner)
                        </center>
                    </td>
                </tr>
            </table>
        </div>
        <div id="signature">
            <table>
                <tr>
                    <td id="shipper-sig">
                        <p class="fp8px">
                            This is to certify that the above name materials are properly classified, described, packaged, marked and labeled, and are in proper condition for transportation according to the applicable regulations of the DOT.
                        </p>
                        <br>
                        SHIPPER SIGNATURE:
                        <span id="sig-date">DATE:</span>
                        <br>
                        <br>
                        <br>
                    </td>
                    <td>
                        <p class="fp8px">
                            Carrier acknowledges receipt of packages and required placards. Carrier certifies emergency response information was made available and/or carrier has the DOT emergency response guide book or equivalent document in the vehicle.
                        </p>
                        <br>
                        DRIVER SIGNATURE:
                        <span id="sig-date">DATE:</span>
                        <br>
                        <br>
                        <br>
                    </td>
                </tr>
            </table>
        </div>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nypformulate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shipments/_form.html.erb
<div class = "col-md-10" id ="window">
<%= simple_form_for @shipment do |f| %><%= f.input :date, class: 'form-control' %><br>
<%= f.input :day, class: 'form-control' %><br>
<%= f.input :truckNumber, class: 'form-control', :label => "Truck of the Day" %><br>
<%= f.input :seal, class: 'form-control' %><br>
<%= f.input :trucker, class: 'form-control', :label => "Carrier" %><br>
<%= f.input :truckernumber, class: 'form-control', :label => "Driver + Phone Number" %><br>
<%= f.input :deliverydate, class: 'form-control', :label => "Delivery Date" %><br>
  <h3>Skids</h3>
     <div id = "skids">
        <%= f.simple_fields_for(:skids) do |skid| %>
            <%= render 'skid_fields', :f => skid %>
        <% end %>
        <div class ="links">
            <%= link_to_add_association 'Add Skid', f, :skids %>
        </div>
     </div>
     <%= f.submit %>
  <% end %>
</div>

app/views/shipments/_skid_fields.html.erb
<div class="nested-fields">
	<div class = "col-md-12" id="fields">
		<div class = "col-md-1">
			<%= f.input :number, class: 'form-control' %>
		</div>

		<div class = "col-md-3">
			<%= f.input :product, class: 'form-control' %>
		</div>

		<div class = "col-md-2">
			<%= f.input :po, class: 'form-control' %>
		</div>

		<div class = "col-md-2">
			<%= f.input :cases, class: 'form-control' %>
		</div>

		<div class = "col-md-2">
			<%= f.input :weight, class: 'form-control' %>
		</div>

		<div class = "col-md-2">
			<%= f.input :breakdown, class: 'form-control' %>
		</div>

		<div class = "col-md-1">
			<button class="remove-button"><%= link_to_remove_association "Remove", f %></button>
		</div>
		
	</div>
</div>

app/views/shipments/edit.html.erb
<div class ="container">
	<h1>Edit a shipment</h1>
	<%= render "form" %>
</div>

app/views/shipments/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>NYP Formulate</title>
	
	<style type="text/css">

	</style>
</head>
<body>
	
	<h1><%= link_to "Add New Shipment", new_shipment_path %></h1><br><br>
	<div class="container">
		<table class="table table-hover">
			<thead>
				<tr>
					<th>Date</th>
					<th>Time of Arrival</th>
					<th>Company</th>
					<th>      </th>
				</tr>
			</thead>
			<tbody>
				<% @shipments.each do |shipment| %>
					<tr>
						<td><%= link_to shipment.date, shipment_path(shipment) %></td>
						<td><%= shipment.truckNumber %></td>
						<td><%= shipment.trucker %></td>
						<td><%= link_to "Delete", shipment_path(shipment), method: :delete, data: {confirm: "Are you sure you want to delete this shipment?"} %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
	
</body>
</html>

app/views/shipments/new.html.erb
<!DOCTYPE html>
<html>
	<head>
	</head>
	<body>
		<div class ="container">
			<h1>Create a new shipment</h1>
			<%= render "form" %>
		</div>
	</body>
</html>

app/views/skids/new.html.erb
<div class ="container">
	<h1>Edit a shipment</h1>
	<%= render "form" %>
</div>